### ISSUE TITLE
Modify default coloring for file output

### ISSUE THREAD

**Issue by thombashi** [thombashi/pytest-md-report#2]
Not apply ANSI color to the reports if the `--md-report-color` option is set to `auto` and the output destination is a file.

_Originally posted by @jasonm23 in https://github.com/thombashi/pytest-md-report/issues/1#issuecomment-1569481954_

**Comment by jasonm23** [comment]
Thank you

**Comment by thombashi** [comment]
@jasonm23 
I added the feature at `pytest-md-report v0.4`.
Please try that version.
