### ISSUE TITLE
Doesn't work with pytest 8.0.0

### ISSUE THREAD

**Issue by FollowTheProcess** [thombashi/pytest-md-report#5]
Hello 👋🏻 

Great project! Just a quick question, is the maximum pytest version of `<8` intentional or just a safety against breaking changes? Do you think this could be relaxed? I'm getting some version conflict issues on some of my projects 🙁 

Happy to submit a PR if it's something you're willing to support, thanks!

**Comment by thombashi** [comment]
@FollowTheProcess 
Hello

>is the maximum pytest version of <8 intentional or just a safety against breaking changes?

The latter is the reason.

>Do you think this could be relaxed? 

I think so.
PRs are welcome.

**Comment by thombashi** [comment]
@FollowTheProcess 
Thank you for your pull request.
I have released a new version of the package.
